import base64
from io import BytesIO

from matplotlib import pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
from skyfield.api import load
from skyfield import almanac
from skyfield import almanac_east_asia as almanac_ea
from zoneinfo import ZoneInfo
from datetime import datetime
from acupuncture.diagnostics import solartime_by_ip
from acupuncture.db import Database

ELEM = ("木", "火", "土", "金", "水")
ELEM_CORRESPOND = [
    ("木", "春", "LR"),
    ("火", "夏", "HT"),
    ("相火", None, "PC"),
    ("土", "長夏", "SP"),
    ("金", "秋", "LU"),
    ("水", "冬", "KI"),
]


class Element:

    def __init__(self):
        self.map_dict = None
        self.translated = None
        self.inhibited = None
        self.G = nx.MultiDiGraph()
        self.lord = None
        self.servant = None
        self.mother = None
        self.son = None
        self.generate_list = None
        self.inhibit_list = None
        self.pos = None

    @staticmethod
    def make_cyclic_edge(lst):
        """Morph linear lists into nested tuples of paired elements
        that represent cyclic data as edges to be graphed."""
        cyclic = []
        for i, elem in enumerate(lst):
            if i + 1 < len(lst):
                cyclic.append((elem, lst[i + 1]))
            else:
                cyclic.append((elem, lst[0]))

        return cyclic

    def base_graph(self, generate, inhibit):
        """Base graph for acute and chronic energy cycles."""

        for pair in generate:
            self.G.add_edge(*pair, color="g", group="generate")

        for pair in inhibit:
            self.G.add_edge(*pair, color="r", group="inhibit")

        return self.G

    def build_position(self, graph, top=None, clockwise=True):
        self.pos = nx.circular_layout(graph, center=(0, 0))

        if top:
            c, s = self.pos[top]
            R_mat = np.array([[-s, c], [c, s]])
            for k, v in self.pos.items():
                self.pos[k] = R_mat @ v

        if not clockwise:
            for k, v in self.pos.items():
                self.pos[k][0] *= -1

        return self.pos

    def build_edges(self, graph):
        self.generate_list = [(u, v, c) for (u, v, c) in graph.edges.data('group') if c == "generate"]
        self.inhibit_list = [(u, v, c) for (u, v, c) in graph.edges.data('group') if c == "inhibit"]

        return self.generate_list, self.inhibit_list

    def generated_by(self, mother, cycle):
        """The returned organ energy i.e. the 「子穴」, is generated by this organ."""
        self.son = [s for m, s in cycle if m == mother]
        return self.son

    def generates(self, son, cycle):
        """The returned organ energy i.e. the 「母穴」, generated this organ's energy."""
        self.mother = [m for m, s in cycle if s == son]
        return self.mother

    def inhibited_by(self, lord, cycle):
        """The returned organ energy is inhibited by this organ."""
        self.inhibited = [l for s, l in cycle if s == lord]
        return self.inhibited

    def servant_of(self, lord, cycle):
        """The returned organ energy is inhibited by this organ."""
        self.servant = [s for s, l in cycle if l == lord]
        return self.servant

    def organ_viscera_lang_map(self, lang):
        """Map organ-viscera ID to a target language for processing or display."""
        col_name = lang + "_name"

        db = Database()
        mapping = db.exec_script(f"""
        SELECT ID, {col_name} FROM Organ_Viscera;
        """)

        self.map_dict = {key: name for key, name in mapping}

        return self.map_dict

    def translate_graph(self, graph, lang):
        """Translate graph node labels to the required language."""

        mapping = self.organ_viscera_lang_map(lang)

        self.translated = nx.relabel_nodes(graph, mapping)

        return self.translated

    def translate_edge_list(self, edge_list, lang):
        """Translate node labels in edge list to the target language."""

        mapping = self.organ_viscera_lang_map(lang)

        self.edge_list = [(mapping[a], mapping[b], n) for a, b, n in edge_list]

        return self.edge_list


class Acute(Element):
    
    ORGAN_ENERGY = [("LR", "木"), ("HT", "火"), ("SP", "土"), ("LU", "金"), ("KI", "水")]

    def __init__(self):
        super().__init__()
        self.viscera = None
        self.organ = None
        self.prescription = None
        self.ELEM_CYCLE_GEN = self.make_cyclic_edge(ELEM)  # 5 element generation cycle edges
        self.ELEM_CYCLE_INHIBIT = self.make_cyclic_edge(("木", "土", "水", "火", "金"))

    def graph(self):
        """Generate energy cycle graph for acute illnesses."""

        self.G = self.base_graph(self.ELEM_CYCLE_GEN, self.ELEM_CYCLE_INHIBIT)

        self.build_edges(self.G)
        self.pos = self.build_position(self.G, top="火")

        plt.figure(1, figsize=(4, 4), dpi=200)

        nx.draw(self.G,
                pos=self.pos,
                with_labels=True,
                font_family='AR PL KaitiM Big5',
                font_size=16,
                node_size=800,
                node_color='#C6DDCB',
                connectionstyle=f"arc3, rad=-0.235",
                edgelist=self.generate_list,
                edge_color="g",
                )

        nx.draw_networkx_edges(self.G,
                               pos=self.pos,
                               node_size=800,
                               edgelist=self.inhibit_list,
                               connectionstyle=f"arc3, rad=0.0",
                               edge_color="r",
                               )

        # plt.show()
        plt.tight_layout()

        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()

        graphic = base64.b64encode(image_png)
        graphic = graphic.decode('utf-8')

        return self.G, graphic

    def organ_to_energy(self, organ):
        energy = [e for o, e in self.ORGAN_ENERGY if organ == o][0]
        return energy

    def energy_to_organ(self, energy):
        organ = [o for o, e in self.ORGAN_ENERGY if energy == e][0]
        return organ

    def organ_viscera_zh(self, organ_id):
        """Get corresponding organ-viscera 臟腑 in Chinese
        from organ id."""
        db = Database()

        self.organ = db.exec_script(f"""
            SELECT zh_name FROM Organ_Viscera
            JOIN Meridian on Meridian.ID = Organ_Viscera.ID
            WHERE Organ_Viscera.ID = "{organ_id}";
        """, fetch_one=True)[0]

        self.viscera = db.exec_script(f"""
            SELECT zh_name FROM Organ_Viscera
            JOIN Meridian on Meridian.ID = Organ_Viscera.ID
            WHERE Organ_Viscera.ID = (
            SELECT related FROM `Meridian`
            WHERE Meridian.ID = "{organ_id}");
        """, fetch_one=True)[0]

        return self.organ, self.viscera

    def relative_states(self, lord):
        """Given the seasonal lord, calculate the organ energy states
        that are related to it."""

        self.mother = self.energy_to_organ(
            self.generates(self.organ_to_energy(lord), self.ELEM_CYCLE_GEN)[0])
        self.son = self.energy_to_organ(
            self.generated_by(self.organ_to_energy(lord), self.ELEM_CYCLE_GEN)[0])
        self.servant = self.energy_to_organ(
            self.servant_of(self.organ_to_energy(lord), self.ELEM_CYCLE_INHIBIT)[0])
        self.inhibited = self.energy_to_organ(
            self.inhibited_by(self.organ_to_energy(lord), self.ELEM_CYCLE_INHIBIT)[0])

        return self.mother, self.son, self.servant, self.inhibited

    def diagnose(self, lord, energy, mother_overload=False):
        """Prescribe formulas according to a diagnosis
        of the seasonal lord meridian's energy level., attrib
        Energy should be given as `+` (excessive) or `-` (deficient). """

        p = Pentashu()
        self.prescription = []

        mother, son, servant, inhibited = self.relative_states(lord)

        if energy == "-":  # 能量不足。

            mother_cardinal = p.cardinal_point_of_meridian(mother)

            if mother_overload:
                # 補君自身與其母之本穴屬性相同的五輸穴。
                self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                    lord, mother_cardinal[1]), "++"))
                # 補其母與君之本穴屬性相同的五輸穴。
                self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                    mother, p.cardinal_point_of_meridian(lord)[1]), "++"))

            else:

                # 補君之母的本穴。
                self.prescription.append((mother_cardinal[0], "++"))
                # 補君自身與其母之本穴屬性相同的五輸穴。
                self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                    lord, mother_cardinal[1]), "++"))
                # 瀉臣的本穴。
                servant_cardinal = p.cardinal_point_of_meridian(servant)
                self.prescription.append((servant_cardinal[0], "--"))
                # 瀉君自身與臣本穴屬性相同的五輸穴。
                self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                    lord, servant_cardinal[1]), "--"))

        else:  # 能量有餘。

            # 補臣的本穴。
            servant_cardinal = p.cardinal_point_of_meridian(servant)
            self.prescription.append((servant_cardinal[0], "++"))
            # 補君自身與臣本穴屬性相同的五輸穴。
            self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                lord, servant_cardinal[1]), "++"))
            # 瀉君之子的本穴。
            son_cardinal = p.cardinal_point_of_meridian(son)
            self.prescription.append((son_cardinal[0], "--"))
            # 瀉君自身與其母之本穴屬性相同的五輸穴。
            self.prescription.append((p.acupoint_of_x_meridian_with_y_qualities(
                lord, son_cardinal[1]), "--"))

        return self.prescription


class Chronic(Element):
    ORGAN_FUNC = (
        "SP",
        "LU",
        "PC",
        "LI",
        "TE",
        "GB",
        "LR",
        "KI",
        "HT",
        "SI",
        "BL",
        "ST",
    )

    ORGAN_FUNC_INHIBIT_A = (
        "BL",
        "SI",
        "LI",
        "GB",
        "ST",
    )

    ORGAN_FUNC_INHIBIT_Am = (
        "TE",
        "LI",
        "GB",
    )

    ORGAN_FUNC_INHIBIT_B = (
        "LR",
        "SP",
        "KI",
        "PC",
        "HT",
        "LU",
    )

    ORGAN_FUNC_INHIBIT_C = (
        "LR",
        "PC",
        "HT",
        "LU",
    )

    ORGAN_FUNC_INHIBIT_D = (
        "BL",
        "TE",
    )

    ORGAN_FUNC_inhibit_list = [
        ORGAN_FUNC_INHIBIT_A,
        ORGAN_FUNC_INHIBIT_Am,
        ORGAN_FUNC_INHIBIT_B,
        ORGAN_FUNC_INHIBIT_C,
        ORGAN_FUNC_INHIBIT_D,
    ]

    def __init__(self):
        super().__init__()
        self.translated = None
        self.ORGAN_FUNC_INHIBIT = []
        self.edges_to_adjust = [("LI", "GB", 0), ("LI", "GB", 1), ("GB", "TE", 0), ("TE", "LI", 0),
                                ("ST", "BL", 0), ("BL", "SI", 0)]

        self.ORGAN_FUNC_GEN = self.make_cyclic_edge(Chronic.ORGAN_FUNC)

        for cycle in self.ORGAN_FUNC_inhibit_list:
            self.ORGAN_FUNC_INHIBIT += self.make_cyclic_edge(cycle)

    def graph(self, zh=True):
        """Generate energy cycle graph for chronic illnesses."""

        self.G = self.base_graph(self.ORGAN_FUNC_GEN, self.ORGAN_FUNC_INHIBIT)

        if zh:
            self.G = self.translate_graph(self.G, "zh")

            self.edges_to_adjust = self.translate_edge_list(self.edges_to_adjust, "zh")

            for edge in self.edges_to_adjust:
                self.G.remove_edge(*edge)  # temporarily remove edges that require a different connection style.

            self.build_edges(self.G)

            self.pos = self.build_position(self.G, top="膀胱")

        else:

            for edge in self.edges_to_adjust:
                self.G.remove_edge(*edge)  # temporarily remove edges that require a different connection style.

            self.build_edges(self.G)

            self.pos = self.build_position(self.G, top="BL")

        plt.figure(2, figsize=(5, 5), dpi=200)

        nx.draw(self.G,
                pos=self.pos,
                with_labels=True,
                font_family='AR PL KaitiM Big5',
                font_size=14,
                node_size=900,
                node_color='#C6DDCB',
                connectionstyle=f"arc3, rad=-0.1",
                edgelist=self.generate_list,
                edge_color="g",
                )

        nx.draw_networkx_edges(self.G,
                               pos=self.pos,
                               node_size=800,
                               edgelist=self.inhibit_list,
                               connectionstyle=f"arc3, rad=-0",
                               edge_color="r",
                               )

        nx.draw_networkx_edges(self.G,
                               pos=self.pos,
                               node_size=800,
                               edgelist=self.edges_to_adjust,  # build back removed edges.
                               connectionstyle=f"arc3, rad=-0.6",
                               edge_color="r",
                               )

        # plt.show()

        buffer = BytesIO()
        plt.savefig(buffer, format='png', bbox_inches='tight')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()

        graphic = base64.b64encode(image_png)
        graphic = graphic.decode('utf-8')

        return self.G, graphic


class Season:
    SEASONS = ["春", "夏", "秋", "冬"]
    SEASON_ENERGY = {
        "春": "木",
        "夏": "火",
        "秋": "金",
        "冬": "水",
    }

    def __init__(self):

        self.season_label = None
        self.earth_energy = None
        self.organ = None
        self.solar_term_date = None
        self.tz = solartime_by_ip()[1]
        self.tz = ZoneInfo(self.tz)  # current time zone, based on ip.
        self.current_date = datetime.now(self.tz)
        self.yr = datetime.now(self.tz).year
        self.db_yr = None

        self.season = None
        self.solar_term = None
        self.season_df = None
        self.solar_term_df = None
        self.season_array = None
        self.terms_array = None

    def update_solar_term_data(self):
        """Check whether solar term data in acu.db is up-to-date."""

        db = Database()
        self.db_yr = db.exec_script("""
        SELECT date_utc FROM seasons WHERE solar_term = "春分";
        """)

        if self.yr != self.db_yr:
            self.build_season_data()

    def load_solar_term_data(self):
        """Load solar term data from skyfield.
        This should be automatically updated once every calendar year."""

        ts = load.timescale()
        eph = load('de421.bsp')  # Covers 1900-2050; use de422 for Chinese History Project

        t0 = ts.utc(self.yr, 1, 1)
        t1 = ts.utc(self.yr, 12, 31)  # relative date one month from now
        t, tm = almanac.find_discrete(t0, t1, almanac_ea.solar_terms(eph))

        solar_term = []
        date = []
        for tmi, ti in zip(tm, t):
            solar_term.append(almanac_ea.SOLAR_TERMS_ZHT[tmi])
            date.append(ti.utc_datetime())

        self.solar_term_df = pd.DataFrame(list(zip(solar_term, date)), columns=["solar_term", "date_utc"])

        return self.solar_term_df

    def season_solar_terms(self):
        jieqi_terms = almanac_ea.SOLAR_TERMS_ZHT[-3:] + almanac_ea.SOLAR_TERMS_ZHT[:-3]
        jieqi_season = [[season] * 6 for season in self.SEASONS]
        jieqi_season = [item for sublist in jieqi_season for item in sublist]

        self.terms_array = np.array(jieqi_terms)
        self.season_array = np.array(jieqi_season)

        return self.terms_array, self.season_array

    def build_season_data(self):

        terms_array, season_array = self.season_solar_terms()
        season_energy = np.vectorize(self.SEASON_ENERGY.get)(list(season_array))
        season_change = np.where(season_array[:-1] != season_array[1:])[
            0]  # 大寒、穀雨、大暑、霜降。「立春」等前一個節氣，約換季前十八天。屬土，宜補脾。《素問·太陰陽明論》：“脾者土也，治中央，常以四時長四藏，各十八日寄治，不得獨主於時也。”

        if season_array[1] != season_array[-1]:
            season_change = np.append(season_change, 23)

        season_dict = {
            "solar_term": terms_array,
            "season": season_array,
            "long_summer": [True if term in ["大暑", "立秋", "處暑"] else False for term in terms_array],  # 夏末跨季一個月
            "energy_5elem": season_energy,
            "earth_energy": [True if term in terms_array[season_change] else False for term in terms_array],
        }  # merge long_summer and inter-season earth_energy to get best timing for treating the spleen.

        season_df = pd.DataFrame(season_dict)
        solar_term_df = self.load_solar_term_data()
        self.season_df = pd.merge(season_df, solar_term_df, on='solar_term', how='outer')

        db = Database()
        db.df_to_sql(self.season_df)

        return self.season_df

    def current_season(self):
        """Return current season, the last solar term (節氣) and the present date."""

        db = Database()
        jieqi = db.exec_script("""
                    SELECT solar_term, season, date_utc, long_summer FROM seasons;
                    """)
        dates = [dt for tm, sn, dt, ls in jieqi]

        for i, dt in enumerate(dates):
            if i + 1 <= len(dates):
                lower_bound = datetime.fromisoformat(dt)
                upper_bound = datetime.fromisoformat(dates[i + 1])

                if lower_bound <= self.current_date < upper_bound:
                    self.solar_term = jieqi[i][0]
                    self.solar_term_date = datetime.fromisoformat(jieqi[i][2]).astimezone(self.tz)
                    self.season = jieqi[i][1]
                    if self.season == "夏" or self.season == "秋" and jieqi[i][3] == 1:
                        self.season_label = self.season + f"（長夏）"
                    else:
                        self.season_label = self.season

                    return self.season, self.solar_term, self.solar_term_date, \
                        self.current_date.astimezone(self.tz), self.tz, self.season_label
            else:
                break

    def seasonal_lord(self, season):
        """Get seasonal lord (organ energy) from season."""
        self.organ = [o for e, s, o in ELEM_CORRESPOND if s == season]
        return self.organ[0]

    def earth_energy_timeframe(self, solar_term):
        """Returns True if season is within the earth energy time frame,
        suitable for treating the Spleen."""

        db = Database()
        self.earth_energy = db.exec_script(f"""
        SELECT earth_energy, long_summer FROM seasons
        WHERE solar_term = "{solar_term}";
        """)[0]
        
        if 1 in self.earth_energy:
            return True


class Pentashu(Acute):

    def __init__(self):
        super().__init__()
        self.map_dict = None
        self.attrib = None
        self.acupoint = None

    def acupoint_of_x_meridian_with_y_qualities(self, x, y):
        """Get Pentashu acupoint of a certain meridian
        belonging to a certain element."""

        db = Database()
        self.acupoint = db.exec_script(f"""
        SELECT ID FROM Pentashu
        WHERE meridian_id = "{x}" and elem = "{y}";
        """)

        return self.acupoint[0][0]

    def cardinal_point_of_meridian(self, m):
        """Get the cardinal point 本穴 of a certain meridian."""

        db = Database()
        self.acupoint = db.exec_script(f"""
        SELECT ID, elem FROM Pentashu
        WHERE meridian_id = "{m}" and cardinal = "1";
        """)

        return self.acupoint[0]

    def get_attributes(self, acupoint):
        """Get attributes of Pentashu acupoint."""
        db = Database()
        self.attrib = db.exec_script(f"""
        SELECT name, meridian_abbrev, elem FROM Pentashu
        WHERE ID = "{acupoint}";
        """)[0]
        return self.attrib[1] + self.attrib[2] + "穴"


if __name__ == '__main__':
    pass
    # p = Pentashu()
    # print(p.acupoint_of_x_meridian_with_y_qualities("LU", "木"))
    # print(p.cardinal_point_of_meridian("LI"))
    # print(p.get_attributes("LU11"))
    # print(p.organ_viscera_lang_map("zh"))

    # x = Acute()
    # print(x.diagnose("LR", "--", True))

    # x = Chronic()
    # print(x.ORGAN_FUNC_INHIBIT)
    # print(x.servant_of("TE", x.ORGAN_FUNC_INHIBIT))  # 剋三焦的
    # print(x.lord_of("PC", set(x.ORGAN_FUNC_INHIBIT)))

    # G = x.graph()


    # print(G.edges.data)
    # G.edges.data = [('脾', 'LU', 0), ('脾', 'KI', 0), ('LU', 'PC', 0), ('LU', 'LR', 0), ('LU', 'LR', 1), ('PC', 'LI', 0), ('PC', 'HT', 0), ('PC', 'HT', 1), ('LI', 'TE', 0), ('TE', 'GB', 0), ('TE', 'BL', 0), ('GB', 'LR', 0), ('GB', 'ST', 0), ('LR', 'KI', 0), ('LR', '脾', 0), ('LR', 'PC', 0), ('KI', 'HT', 0), ('KI', 'PC', 0), ('HT', 'SI', 0), ('HT', 'LU', 0), ('HT', 'LU', 1), ('SI', 'BL', 0), ('SI', 'LI', 0), ('BL', 'ST', 0), ('BL', 'TE', 0), ('ST', '脾', 0)]
    #
    # y = Acute()
    # y.graph()

    z = Season()
    print(z.earth_energy_timeframe("芒種"))
    # this_season = z.current_season()[1]
    #
    # print(z.seasonal_lord("春"))
